version: '3.8'

services:
  pulsespeed-api:
    build: .
    container_name: pulsespeed_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - DATABASE_URL=postgres://pulsespeed:pulsepass@postgres:5432/speedtest
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: pulsespeed_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: pulsespeed
      POSTGRES_PASSWORD: pulsepass
      POSTGRES_DB: speedtest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  pgdata:
